version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      POSTGRES_DB: tech
    ports:
      - "15432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
